name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install Windows toolchain
      run: rustup target add x86_64-pc-windows-gnu
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --verbose --target x86_64-pc-windows-gnu -r
